# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluateteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from total_scores import Ui_Dialog as Score
import sqlite3
match= sqlite3.connect("cricket_db.db")
matchcur=match.cursor()

class Ui_evaluate_team(object):
    def __init__(self):  #initialising score window
        self.scoreDialog = QtWidgets.QMainWindow()
        self.score_screen = Score()
        self.score_screen.setupUi(self.scoreDialog)


    def setupUi(self, evaluate_team):
        evaluate_team.setObjectName("evaluate_team")
        evaluate_team.resize(576, 495)
        evaluate_team.setStyleSheet("background-color: rgb(199, 199, 199);\n"
"background-color: rgb(85, 170, 255);")
        self.label = QtWidgets.QLabel(evaluate_team)
        self.label.setGeometry(QtCore.QRect(90, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.s_team = QtWidgets.QComboBox(evaluate_team)
        self.s_team.setGeometry(QtCore.QRect(90, 70, 141, 21))
        self.s_team.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 10pt \"Century Gothic\";")
        self.s_team.setObjectName("s_team")
        self.s_team.addItem("")
        self.s_match = QtWidgets.QComboBox(evaluate_team)
        self.s_match.setEnabled(True)
        self.s_match.setGeometry(QtCore.QRect(360, 70, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.s_match.setFont(font)
        self.s_match.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 11pt \"Century Gothic\";")
        self.s_match.setObjectName("s_match")
        self.s_match.addItem("")
        self.s_match.addItem("")
        self.line = QtWidgets.QFrame(evaluate_team)
        self.line.setGeometry(QtCore.QRect(40, 95, 551, 41))
        self.line.setStyleSheet("color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(evaluate_team)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(evaluate_team)
        self.label_3.setGeometry(QtCore.QRect(350, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.total_score = QtWidgets.QPushButton(evaluate_team)
        self.total_score.setEnabled(True)
        self.total_score.setGeometry(QtCore.QRect(240, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.total_score.setFont(font)
        self.total_score.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.total_score.setAutoDefault(False)
        self.total_score.setObjectName("total_score")
        self.playr_name = QtWidgets.QListWidget(evaluate_team)
        self.playr_name.setGeometry(QtCore.QRect(80, 180, 191, 221))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.playr_name.setFont(font)
        self.playr_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.playr_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playr_name.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.playr_name.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.playr_name.setObjectName("playr_name")
        self.playr_score = QtWidgets.QListWidget(evaluate_team)
        self.playr_score.setGeometry(QtCore.QRect(340, 180, 191, 221))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.playr_score.setFont(font)
        self.playr_score.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.playr_score.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playr_score.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.playr_score.setObjectName("playr_score")

        self.retranslateUi(evaluate_team)
        QtCore.QMetaObject.connectSlotsByName(evaluate_team)
        self.total_score.clicked.connect(self.final_score)
        se_team = self.s_team.currentText()

        self.changedname(se_team)
        self.s_team.currentTextChanged.connect(self.changedname)
        


    def retranslateUi(self, evaluate_team):
        _translate = QtCore.QCoreApplication.translate
        evaluate_team.setWindowTitle(_translate("evaluate_team", "Dialog"))
        self.label.setText(_translate("evaluate_team", "Evaluate the Performance of your Fantasy Team"))
        self.s_team.setCurrentText(_translate("evaluate_team", "Select team"))
        self.s_team.setItemText(0, _translate("evaluate_team", "Select team"))
        self.s_match.setItemText(0, _translate("evaluate_team", "select match"))
        self.s_match.setItemText(1, _translate("evaluate_team", "Match1"))
        self.label_2.setText(_translate("evaluate_team", "Players"))
        self.label_3.setText(_translate("evaluate_team", "Points"))
        self.total_score.setStatusTip(_translate("evaluate_team", "calculating score"))
        self.total_score.setText(_translate("evaluate_team", "Calculate Score"))
        x = matchcur.execute("SELECT  DISTINCT name from teams;")
        team = x.fetchall()
        for i in team:
            self.s_team.addItem(i[0])
    def changedname(self, t):
        self.playr_name.clear()
        self.playr_score.clear()
        y = matchcur.execute("SELECT players from teams WHERE name='" + t + "';")
        player = y.fetchall()
        
        # print('player',player)
        for j in player:
            self.playr_name.addItem(j[0])
        z = matchcur.execute("SELECT value from teams WHERE name='" + t + "';")
        value = z.fetchall()
        for k in value:
            self.playr_score.addItem(str(k[0]))


    def final_score(self):
        total_score=0
        t=self.s_team.currentText()   # current teamname
        # print(t)
        z = matchcur.execute("SELECT value from teams WHERE name='" + t + "';")
        value = z.fetchall()
       
        # print('value', value)
        for k in value:
            total_score+=k[0]
        self.score_screen.finalscore.setText(str(total_score))  # opening score dialog box and setting final score
        self.scoreDialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evaluate_team = QtWidgets.QDialog()
    ui = Ui_evaluate_team()
    ui.setupUi(evaluate_team)
    evaluate_team.show()
    sys.exit(app.exec_())
